from django.urls import path, include
from rest_framework_nested import routers
from .views import AuthViewSet, UserViewSet, ConversationViewSet, MessageViewSet

# Initialize main router
router = routers.DefaultRouter()
router.register(r'users', UserViewSet, basename='user')
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'auth', AuthViewSet, basename='auth')
# Create nested router for messages under conversations
conversations_router = routers.NestedDefaultRouter(
    router, r'conversations', lookup='conversation'
)
conversations_router.register(r'messages', MessageViewSet, basename='conversation-messages')

# Register standalone messages endpoint
router.register(r'messages', MessageViewSet, basename='message')

# Auth endpoints
urlpatterns = [
    path('', include(router.urls)),
    path('', include(conversations_router.urls)),
]
# This file defines the URL patterns for the messaging application.
# It includes routes for user management, conversation handling, and message operations.
# The urlpatterns list is initialized as empty and will be populated with paths for the API endpoints.
# Import necessary modules and viewsets for routing
# router = routers.NestedDefaultRouter()
# router.register(r'users', UserViewSet, basename='user')
# router.register(r'conversations', ConversationViewSet, basename='conversation')
# router.register(r'conversations/(?P<conversation_pk>[^/.]+)/messages', MessageViewSet, basename='conversation-messages')
# router.register(r'auth', AuthViewSet, basename='auth')
# urlpatterns += router.urls
# The urlpatterns list is extended with the URLs generated by the router.
# urlpatterns += [
#     path('api/v1/', include(router.urls)),
# ]
